import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
OWNER_TELEGRAM_ID = int(os.getenv("OWNER_TELEGRAM_ID"))
DATABASE_URL = os.getenv("DATABASE_URL")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
WHISPER_MODEL = os.getenv("WHISPER_MODEL", "base")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

LEAD_THRESHOLD = 7.0
SESSION_HOURS = 24
ACTIVE_SESSION_GRACE_MINUTES = 90
MAX_CONTEXT_MEMORIES = 3
MAX_CONTEXT_EVENTS = 5
MAX_SUMMARY_CHARS = 500