import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import (
    DEEPSEEK_API_KEY,
    GEMINI_API_KEY,
    OPENAI_API_KEY,
    OPENROUTER_API_KEY,
    INITIAL_SCORES,
    SCORE_SUCCESS_INCREMENT,
    SCORE_FAILURE_PENALTY,
    MAX_SCORE,
    MIN_SCORE,
    CONSECUTIVE_FAILURES_THRESHOLD,
    COOLDOWN_SECONDS,
    DAILY_BUDGET,
    MONTHLY_BUDGET,
    FREE_PROVIDERS,
    REDIS_URL,
)

OPENROUTER_FREE_MODELS = []

__all__ = [
    "DEEPSEEK_API_KEY",
    "GEMINI_API_KEY",
    "OPENAI_API_KEY",
    "OPENROUTER_API_KEY",
    "OPENROUTER_FREE_MODELS",
    "INITIAL_SCORES",
    "SCORE_SUCCESS_INCREMENT",
    "SCORE_FAILURE_PENALTY",
    "MAX_SCORE",
    "MIN_SCORE",
    "CONSECUTIVE_FAILURES_THRESHOLD",
    "COOLDOWN_SECONDS",
    "DAILY_BUDGET",
    "MONTHLY_BUDGET",
    "FREE_PROVIDERS",
    "REDIS_URL",
]